template-arb-file: tr_TR.arb
nullable-getter: false
synthetic-package: false
output-localization-file: app_localizations.dart
arb-dir: lib/core/localization/languages
output-dir: lib/core/localization/l10n