name: artevo
description: Günlük Estetik Seçkiler
publish_to: 'none'
version: 2.0.0+25

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #-- core
  artevo_package:
    path: ../artevo_package
  flutter_riverpod: ^2.3.6

  #-- loacalization
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

  #-
  timezone: ^0.9.3
  flutter_timezone: ^1.0.8

  #-- network
  http: ^1.2.1

  #-- firebase
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  firebase_database: ^10.5.5

  #-- admob
  google_mobile_ads: ^5.1.0

  #-- local db  
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.2
  flutter_cache_manager: ^3.3.1

  #-- notifications
  flutter_local_notifications: ^17.1.2

  #----> UI
  iconsax: ^0.0.8
  ionicons: ^0.2.2
  widget_zoom: ^0.0.4
  text_scroll: ^0.2.0
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.2.0+1
  salomon_bottom_bar: ^3.3.2
  flutter_staggered_grid_view: ^0.7.0

  #-- audio player 
  just_audio: ^0.9.37
  audio_session: ^0.1.19
  audio_service: ^0.18.13
  audio_video_progress_bar: ^2.0.2

  #-- OTHERS
  path: ^1.9.0
  uuid: ^4.3.3
  rxdart: ^0.27.7
  collection: ^1.18.0
  url_launcher: ^6.1.11
  in_app_review: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  ios: false
  android: true # or "launcher_icon" spesific name
  min_sdk_android: 21 # android min sdk min:16, default 21

  image_path_android: "assets/app/logo.png"
  image_path_ios: "assets/app/logo.png"
  adaptive_icon_background: "assets/app/background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/app/logo.png" # only available for Android 8.0 devices and above
  adaptive_icon_monochrome: "assets/app/logo.png" # only available for Android 13 devices and above

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/app/
    - assets/fonts/
    - assets/license/
    - assets/ornaments/

  fonts:
    - family: Domine
      fonts:
        - asset: assets/fonts/domine/Domine-Bold.ttf
        - asset: assets/fonts/domine/Domine-Medium.ttf
        - asset: assets/fonts/domine/Domine-Regular.ttf
        - asset: assets/fonts/domine/Domine-SemiBold.ttf
    - family: Chomsky
      fonts:
        - asset: assets/fonts/chomsky/Chomsky.otf
