name: artevo
description: Günlük Estetik Seçkiler
publish_to: 'none'
version: 2.0.0+23

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  artevo_package:
    git:
      url: https://github.com/opiasdream/artevo_package.git
      ref: main

  #-- core
  flutter_riverpod: ^2.3.6
  #-- loacalization
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  #-
  timezone: ^0.9.2
  flutter_timezone: ^1.0.8
  #-- google services
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.5
  firebase_database: ^10.4.6
  google_mobile_ads: ^4.0.0
  #-- cache
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_cache_manager: ^3.3.1
  #-- ui
  iconsax: ^0.0.8
  flutter_svg: ^2.0.9
  zoom_widget: ^2.0.1
  cupertino_icons: ^1.0.2
  flutter_animate: ^4.2.0+1
  #-- for audio player 
  just_audio: ^0.9.35
  audio_service: ^0.18.12
  just_audio_background: ^0.0.1-beta.11
  #-- notifications
  flutter_local_notifications: ^16.2.0
  #-- network
  dio: ^5.4.0
  #-- others
  uuid: ^4.3.3
  url_launcher: ^6.1.11
  in_app_review: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  ios: false
  android: true # or "launcher_icon" spesific name
  min_sdk_android: 21 # android min sdk min:16, default 21

  image_path_android: "assets/app/logo.png"
  image_path_ios: "assets/app/logo.png"
  adaptive_icon_background: "assets/app/background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/app/logo.png" # only available for Android 8.0 devices and above
  adaptive_icon_monochrome: "assets/app/logo.png" # only available for Android 13 devices and above

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/app/
    - assets/fonts/
    - assets/license/
    - assets/music_platforms/
    - assets/ornaments/

  fonts:
    - family: Domine
      fonts:
        - asset: assets/fonts/domine/Domine-Bold.ttf
        - asset: assets/fonts/domine/Domine-Medium.ttf
        - asset: assets/fonts/domine/Domine-Regular.ttf
        - asset: assets/fonts/domine/Domine-SemiBold.ttf
    - family: Chomsky
      fonts:
        - asset: assets/fonts/chomsky/Chomsky.otf
